import { generateId } from '@faasjs/utils'
import { type Dispatch, type SetStateAction, useSyncExternalStore } from 'react'

/**
 * Ref object exposed by {@link createWindowStates} for reading the latest shared state value.
 *
 * @template T - Shared state value type.
 */
export type WindowStateRef<T> = Readonly<{
  current: T
}>

/**
 * Hook map generated by {@link createWindowStates} for each shared state key.
 *
 * @template T - Shared state object shape.
 */
export type WindowStateHooks<T> = {
  [K in keyof T as K extends string ? `use${Capitalize<K>}` : never]: () => T[K]
}

/**
 * Setter map generated by {@link createWindowStates} for each shared state key.
 *
 * @template T - Shared state object shape.
 */
export type WindowStateSetters<T> = {
  [K in keyof T as K extends string ? `set${Capitalize<K>}` : never]: Dispatch<SetStateAction<T[K]>>
}

/**
 * Ref map generated by {@link createWindowStates} for each shared state key.
 *
 * @template T - Shared state object shape.
 */
export type WindowStateRefs<T> = {
  [K in keyof T as K extends string ? `${K}Ref` : never]: WindowStateRef<T[K]>
}

/**
 * Shared state helpers returned by {@link createWindowStates}.
 *
 * @template T - Shared state object shape.
 */
export type WindowStates<T> = WindowStateHooks<T> & WindowStateSetters<T> & WindowStateRefs<T>

type MutableWindowStateRef<T> = {
  current: T
}

type WindowStateSnapshot<T> = {
  value: T
  version: number
}

function upperFirst(value: string) {
  return `${value.charAt(0).toUpperCase()}${value.slice(1)}`
}

function createWindowState<T>(defaultValue: T) {
  const eventName = generateId('createWindowStates:')
  const ref: MutableWindowStateRef<T> = { current: defaultValue }
  let snapshot: WindowStateSnapshot<T> = { value: defaultValue, version: 0 }

  const getSnapshot = () => snapshot

  const subscribe = (onStoreChange: () => void) => {
    if (typeof window === 'undefined') return () => {}

    window.addEventListener(eventName, onStoreChange)

    return () => {
      window.removeEventListener(eventName, onStoreChange)
    }
  }

  const use = () => useSyncExternalStore(subscribe, getSnapshot, getSnapshot).value

  const set: Dispatch<SetStateAction<T>> = (value) => {
    const nextValue =
      typeof value === 'function' ? (value as (previousValue: T) => T)(ref.current) : value

    ref.current = nextValue
    snapshot = {
      value: nextValue,
      version: snapshot.version + 1,
    }

    if (typeof window !== 'undefined')
      window.dispatchEvent(new CustomEvent(eventName, { detail: nextValue }))
  }

  return {
    ref: ref as WindowStateRef<T>,
    set,
    use,
  }
}

/**
 * Create window-backed shared states with generated hooks, setters, and latest-value refs.
 *
 * Each key receives an independent internally generated window event name. Components using
 * a generated hook re-render when the matching setter runs, and code outside React can read
 * the latest value from the generated ref.
 *
 * @template T - Shared state object shape.
 * @param {T} defaultStates - Initial values used to create shared state entries.
 * @returns {WindowStates<T>} Generated `useXxx`, `setXxx`, and `xxxRef` helpers for each key.
 *
 * @example
 * ```tsx
 * import { createWindowStates } from '@faasjs/react'
 *
 * export const { useText, setText, textRef } = createWindowStates({
 *   text: '',
 * })
 *
 * function Preview() {
 *   const text = useText()
 *
 *   return <span>{text}</span>
 * }
 *
 * setText('updated')
 * console.log(textRef.current)
 * ```
 */
export function createWindowStates<T extends Record<string, unknown>>(
  defaultStates: T,
): WindowStates<T> {
  const states = {} as WindowStates<T>

  for (const key of Object.keys(defaultStates) as (keyof T & string)[]) {
    const state = createWindowState(defaultStates[key])
    const name = upperFirst(key)

    Object.assign(states, {
      [`${key}Ref`]: state.ref,
      [`set${name}`]: state.set,
      [`use${name}`]: state.use,
    })
  }

  return states
}
