import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import { tmpdir } from 'node:os'
import { join, relative } from 'node:path'

import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'

import { action } from '../../action'

let execs: string[] = []

const adminGeneratedFaasTypes = `/**
 * Generated by @faasjs/dev.
 *
 * Do not edit this file manually.
 */
import type { InferFaasAction } from '@faasjs/types'

declare module '@faasjs/types' {
  interface FaasActions {
    "features/auth/api/me": InferFaasAction<typeof import("../features/auth/api/me.api")>
    "features/users/api/create": InferFaasAction<typeof import("../features/users/api/create.api")>
    "features/users/api/detail": InferFaasAction<typeof import("../features/users/api/detail.api")>
    "features/users/api/list": InferFaasAction<typeof import("../features/users/api/list.api")>
    "features/users/api/update": InferFaasAction<typeof import("../features/users/api/update.api")>
  }
}
`

const minimalGeneratedFaasTypes = `/**
 * Generated by @faasjs/dev.
 *
 * Do not edit this file manually.
 */
import type { InferFaasAction } from '@faasjs/types'

declare module '@faasjs/types' {
  interface FaasActions {
    "features/home/api/hello": InferFaasAction<typeof import("../features/home/api/hello.api")>
  }
}
`

function writeGeneratedFaasTypes(projectName: string): void {
  const projectRoot = join(process.cwd(), projectName)
  const outputDir = join(projectRoot, 'src', '.faasjs')
  const isAdmin = existsSync(join(projectRoot, 'src', 'features', 'users', 'api', 'list.api.ts'))

  mkdirSync(outputDir, {
    recursive: true,
  })
  writeFileSync(
    join(outputDir, 'types.d.ts'),
    isAdmin ? adminGeneratedFaasTypes : minimalGeneratedFaasTypes,
  )
}

vi.mock('node:child_process', () => ({
  execSync(cmd: string) {
    execs.push(cmd)

    const typesCommand = /^cd ([^ ]+) && npm run types$/.exec(cmd)
    if (typesCommand) writeGeneratedFaasTypes(typesCommand[1])
  },
}))

const adminFiles = [
  '.env.example',
  '.gitignore',
  'index.html',
  'package.json',
  'server.ts',
  'src/.faasjs/types.d.ts',
  'src/db/migrations/20250101000000_create_users.ts',
  'src/db/tables/users.ts',
  'src/faas.yaml',
  'src/features/auth/api/__tests__/me.test.ts',
  'src/features/auth/api/me.api.ts',
  'src/features/users/api/__tests__/create.test.ts',
  'src/features/users/api/__tests__/detail.test.ts',
  'src/features/users/api/__tests__/list.test.ts',
  'src/features/users/api/__tests__/update.test.ts',
  'src/features/users/api/create.api.ts',
  'src/features/users/api/detail.api.ts',
  'src/features/users/api/list.api.ts',
  'src/features/users/api/update.api.ts',
  'src/features/users/index.tsx',
  'src/main.tsx',
  'src/plugins/auth.ts',
  'src/types/faasjs-auth.d.ts',
  'tsconfig.json',
  'vite.config.ts',
]

const minimalFiles = [
  '.gitignore',
  'index.html',
  'package.json',
  'server.ts',
  'src/.faasjs/types.d.ts',
  'src/faas.yaml',
  'src/features/home/api/__tests__/hello.test.ts',
  'src/features/home/api/hello.api.ts',
  'src/features/home/index.tsx',
  'src/main.tsx',
  'src/react-client.ts',
  'tsconfig.json',
  'vite.config.ts',
]

function listFiles(rootPath: string): string[] {
  const files: string[] = []

  function walk(currentPath: string): void {
    for (const entry of readdirSync(currentPath, { withFileTypes: true })) {
      const nextPath = join(currentPath, entry.name)

      if (entry.isDirectory()) {
        walk(nextPath)
        continue
      }

      files.push(relative(rootPath, nextPath))
    }
  }

  walk(rootPath)

  return files.sort()
}

function read(rootPath: string, path: string): string {
  return readFileSync(join(rootPath, path), 'utf8')
}

function expectGeneratedSessionSecret(content: string): void {
  expect(content).toMatch(/secret: '?[a-f0-9]{64}'?/)
  expect(content).not.toContain('secret: secret')
  expect(content).not.toContain('{{secret}}')
}

describe('action', () => {
  let currentDir = ''
  let tempDir = ''

  beforeEach(() => {
    execs = []
    currentDir = process.cwd()
    tempDir = mkdtempSync(join(tmpdir(), 'create-faas-app-'))
    process.chdir(tempDir)
  })

  afterEach(() => {
    process.chdir(currentDir)
    rmSync(tempDir, {
      recursive: true,
      force: true,
    })
  })

  it('should create the admin template by default', async () => {
    await action({
      name: 'admin-app',
    })

    const rootPath = join(tempDir, 'admin-app')
    const packageJSON = JSON.parse(read(rootPath, 'package.json'))

    expect(execs).toEqual([
      'cd admin-app && npm install',
      'cd admin-app && npm run types',
      'cd admin-app && npm run test',
    ])
    expect(listFiles(rootPath)).toEqual(adminFiles)
    expect(packageJSON.name).toBe('admin-app')
    expect(read(rootPath, 'package.json')).not.toContain('{{name}}')
    expect(read(rootPath, 'package.json')).toContain('"types": "faas types"')
    expectGeneratedSessionSecret(read(rootPath, 'src/faas.yaml'))
    expect(read(rootPath, 'server.ts')).toContain("import { loadEnvFile } from 'node:process'")
    expect(read(rootPath, 'server.ts')).toContain('try {')
    expect(read(rootPath, 'server.ts')).toContain('loadEnvFile()')
    expect(read(rootPath, 'server.ts')).toContain(
      "console.warn('[faasjs] Failed to load env file', error)",
    )
    expect(read(rootPath, '.env.example')).toContain('DATABASE_URL=postgres://')
    expect(read(rootPath, 'src/db/migrations/20250101000000_create_users.ts')).toContain(
      "builder.createTable('users'",
    )
    expect(read(rootPath, 'src/features/users/api/create.api.ts')).toContain(
      "import { getClient } from '@faasjs/pg'",
    )
    expect(read(rootPath, 'src/features/users/api/list.api.ts')).toContain("orderBy('id', 'DESC')")
    expect(read(rootPath, 'src/features/users/api/detail.api.ts')).toContain(
      "message: 'User not found'",
    )
    expect(read(rootPath, 'src/features/users/api/update.api.ts')).toContain(
      'message: `Updated user #${user.id}`',
    )
    expect(read(rootPath, 'src/features/users/api/__tests__/create.test.ts')).toContain(
      "import { getClient } from '@faasjs/pg'",
    )
    expect(read(rootPath, 'src/features/auth/api/me.api.ts')).toContain(
      'api.plugins.unshift(new AuthPlugin())',
    )
    expect(read(rootPath, 'src/features/auth/api/__tests__/me.test.ts')).toContain(
      "authorization: 'Bearer demo-admin'",
    )
    expect(read(rootPath, 'src/plugins/auth.ts')).toContain('class AuthPlugin')
    expect(read(rootPath, 'src/types/faasjs-auth.d.ts')).toContain('interface DefineApiInject')
    expect(read(rootPath, 'src/.faasjs/types.d.ts')).toContain('Generated by @faasjs/dev')
    expect(read(rootPath, 'src/.faasjs/types.d.ts')).toContain(
      '"features/users/api/list": InferFaasAction<typeof import("../features/users/api/list.api")>',
    )
    expect(read(rootPath, 'src/features/users/index.tsx')).not.toContain(
      "declare module '@faasjs/types'",
    )
    expect(read(rootPath, 'src/db/tables/users.ts')).toContain('interface Tables')
    expect(read(rootPath, 'vite.config.ts')).toContain(
      "import { PgVitestPlugin } from '@faasjs/pg-dev'",
    )
    expect(read(rootPath, 'src/main.tsx')).toContain("import { App } from '@faasjs/ant-design'")
    expect(read(rootPath, 'src/features/users/index.tsx')).toContain(
      "import { faas, useApp } from '@faasjs/ant-design'",
    )
    expect(read(rootPath, 'src/features/users/index.tsx')).toContain(
      "useFaas('features/users/api/list'",
    )
    expect(read(rootPath, 'src/features/users/index.tsx')).toContain('Call auth plugin demo')
    expect(read(rootPath, 'src/features/users/index.tsx')).toContain('Load users slice')
    expect(listFiles(rootPath)).not.toContain('src/react-client.ts')
  })

  it('should create the minimal template when requested', async () => {
    await action({
      name: 'minimal-app',
      template: 'minimal',
    })

    const rootPath = join(tempDir, 'minimal-app')
    const packageJSON = JSON.parse(read(rootPath, 'package.json'))

    expect(execs).toEqual([
      'cd minimal-app && npm install',
      'cd minimal-app && npm run types',
      'cd minimal-app && npm run test',
    ])
    expect(listFiles(rootPath)).toEqual(minimalFiles)
    expect(packageJSON.name).toBe('minimal-app')
    expect(read(rootPath, 'package.json')).not.toContain('{{name}}')
    expect(read(rootPath, 'package.json')).toContain('"types": "faas types"')
    expectGeneratedSessionSecret(read(rootPath, 'src/faas.yaml'))
    expect(read(rootPath, 'server.ts')).toContain("import { loadEnvFile } from 'node:process'")
    expect(read(rootPath, 'server.ts')).toContain('try {')
    expect(read(rootPath, 'server.ts')).toContain('loadEnvFile()')
    expect(read(rootPath, 'server.ts')).toContain(
      "console.warn('[faasjs] Failed to load env file', error)",
    )
    expect(read(rootPath, 'src/features/home/api/hello.api.ts')).toContain(
      'export default defineApi(',
    )
    expect(read(rootPath, 'src/features/home/api/__tests__/hello.test.ts')).toContain(
      "import api from '../hello.api'",
    )
    expect(read(rootPath, 'src/react-client.ts')).toContain(
      "import { FaasReactClient } from '@faasjs/react'",
    )
    expect(read(rootPath, 'src/features/home/index.tsx')).toContain(
      "import { useFaas } from '../../react-client'",
    )
    expect(read(rootPath, 'src/features/home/index.tsx')).toContain(
      "useFaas(\n    'features/home/api/hello'",
    )
    expect(read(rootPath, 'src/.faasjs/types.d.ts')).toContain('Generated by @faasjs/dev')
    expect(read(rootPath, 'src/.faasjs/types.d.ts')).toContain(
      '"features/home/api/hello": InferFaasAction<typeof import("../features/home/api/hello.api")>',
    )
    expect(read(rootPath, 'src/features/home/index.tsx')).not.toContain(
      "declare module '@faasjs/types'",
    )
    expect(read(rootPath, 'src/features/home/index.tsx')).toContain('FaasJS Minimal App')
  })

  it('should reject an unknown template', async () => {
    await expect(
      action({
        name: 'broken-app',
        template: 'unknown',
      }),
    ).rejects.toThrow('Unknown template "unknown". Available templates: admin, minimal')

    expect(execs).toEqual([])
  })
})
