import { existsSync } from 'node:fs'
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join, relative } from 'node:path'

import { Logger } from '@faasjs/node-utils'

import { resolveApiRouteFromFile } from '../utils/api-route.ts'
import { resolveServerConfig } from '../utils/server-config.ts'

type RouteTypeItem = {
  route: string
  importPath: string
  priority: number
}

type JobTypeItem = {
  jobPath: string
  importPath: string
  file: string
}

/**
 * Options for generating `@faasjs/types` API and job declarations.
 */
export type GenerateFaasTypesOptions = {
  /**
   * Project root passed through FaasJS server config resolution.
   *
   * When `src/faas.yaml` contains `defaults.server.root`, generation runs from that
   * resolved project root and emits `src/.faasjs/types.d.ts` beneath it.
   *
   * @default process.cwd()
   */
  root?: string
  /**
   * Logger used to report generation progress.
   */
  logger?: Logger
}

/**
 * Summary returned by {@link generateFaasTypes}.
 */
export type GenerateFaasTypesResult = {
  /**
   * Output path of the generated declaration file.
   */
  output: string
  /**
   * Whether the generator wrote new content to disk.
   */
  changed: boolean
  /**
   * Number of `*.api.ts` files discovered under `src/`, including files that lose
   * route precedence to a more specific file.
   */
  fileCount: number
  /**
   * Number of route entries emitted into the declaration file after duplicate
   * routes are resolved by precedence.
   */
  routeCount: number
  /**
   * Number of `.job.ts` paths emitted into the declaration file.
   */
  jobCount: number
}

function toTypegenRoute(route: string): string {
  return route === '/' ? '/' : route.replace(/^\/+/, '')
}

function toRoute(srcRoot: string, file: string): { route: string; priority: number } {
  const route = resolveApiRouteFromFile(srcRoot, file)

  if (!route) throw Error(`[faas types] Invalid API filename: ${file}`)

  return route
}

function toJobPath(srcRoot: string, file: string): string {
  let jobPath = relative(srcRoot, file).replace(/\\/g, '/')

  if (!jobPath.endsWith('.job.ts')) throw Error(`[faas types] Invalid job filename: ${file}`)

  jobPath = jobPath.slice(0, -'.job.ts'.length)

  if (jobPath === 'index') return ''
  if (jobPath.endsWith('/index')) return jobPath.slice(0, -'/index'.length)

  return jobPath
}

function toImportPath(fromFile: string, targetFile: string): string {
  const importPath = relative(dirname(fromFile), targetFile)
    .replace(/\\/g, '/')
    .replace(/\.ts$/, '')

  if (importPath.startsWith('.')) return importPath

  return `./${importPath}`
}

async function readTypegenFiles(dir: string): Promise<{
  apiFiles: string[]
  jobFiles: string[]
}> {
  const apiFiles: string[] = []
  const jobFiles: string[] = []
  const pendingDirs = [dir]

  while (pendingDirs.length) {
    const currentDir = pendingDirs.pop() as string
    const entries = await readdir(currentDir, {
      withFileTypes: true,
    })

    for (const entry of entries) {
      if (entry.name === '.faasjs' || entry.name === 'dist' || entry.name === 'node_modules')
        continue

      const filePath = join(currentDir, entry.name)

      if (entry.isDirectory()) {
        pendingDirs.push(filePath)
        continue
      }

      if (!entry.isFile()) continue

      if (entry.name.endsWith('.api.ts')) apiFiles.push(filePath)
      else if (entry.name.endsWith('.job.ts')) jobFiles.push(filePath)
    }
  }

  return {
    apiFiles: apiFiles.sort((a, b) => a.localeCompare(b)),
    jobFiles: jobFiles.sort((a, b) => a.localeCompare(b)),
  }
}

function formatTypes(routeItems: RouteTypeItem[], jobItems: JobTypeItem[]): string {
  const actionLines = routeItems.map((item) => {
    return `    ${JSON.stringify(toTypegenRoute(item.route))}: InferFaasAction<typeof import(${JSON.stringify(item.importPath)})>`
  })
  const jobLines = jobItems.map((item) => {
    return `    ${JSON.stringify(item.jobPath)}: InferFaasJob<typeof import(${JSON.stringify(item.importPath)})>`
  })
  const imports = jobLines.length ? 'InferFaasAction, InferFaasJob' : 'InferFaasAction'
  const jobsDeclaration = jobLines.length
    ? `
  interface FaasJobs {
${jobLines.join('\n')}
  }
`
    : ''

  return `/**
 * Generated by @faasjs/dev.
 *
 * Do not edit this file manually.
 */
import type { ${imports} } from '@faasjs/types'

declare module '@faasjs/types' {
  interface FaasActions {
${actionLines.length ? `${actionLines.join('\n')}\n` : ''}  }
${jobsDeclaration}}
`
}

/**
 * Determine whether a file change should trigger Faas type generation.
 *
 * API and job files affect generated declarations directly. `faas.yaml` and
 * `faas.yml` files can affect the resolved server root, so watchers should treat
 * them as typegen inputs as well.
 *
 * @param {string} filePath - Absolute or relative path reported by a file watcher.
 * @returns `true` when the changed file can affect generated route declarations.
 * @example
 * ```ts
 * import { isTypegenInputFile } from '@faasjs/dev'
 *
 * isTypegenInputFile('src/orders/create.api.ts') // true
 * isTypegenInputFile('src/orders/process.job.ts') // true
 * isTypegenInputFile('src/orders/service.ts') // false
 * ```
 */
export function isTypegenInputFile(filePath: string): boolean {
  return (
    filePath.endsWith('.api.ts') ||
    filePath.endsWith('.job.ts') ||
    /(^|[\\/])faas\.ya?ml$/.test(filePath)
  )
}

/**
 * Generate `src/.faasjs/types.d.ts` for a FaasJS project.
 *
 * The generator scans the `src/` tree for `.api.ts` and `.job.ts` files. API
 * names become routes, while job names become path identifiers with `.job.ts`
 * removed and trailing `/index` collapsed. Duplicate job paths are rejected.
 * API route precedence is: regular `*.api.ts` files, then `index.api.ts`, then
 * fallback `default.api.ts` files.
 *
 * Generated route keys omit the leading slash except for `/`; for example,
 * `src/users/default.api.ts` becomes `users/*`.
 *
 * @param {GenerateFaasTypesOptions} [options] - Project root and logger overrides.
 * @param {string} [options.root] - Project root used to resolve `src/` and the output file.
 * @param {Logger} [options.logger] - Logger used to report generation progress.
 * @returns Summary describing the generated file, routes, and jobs.
 * @throws {Error} When the resolved `src/` directory does not exist.
 * @example
 * ```ts
 * import { generateFaasTypes } from '@faasjs/dev'
 *
 * const result = await generateFaasTypes({
 *   root: process.cwd(),
 * })
 *
 * console.log(result.output, result.routeCount, result.jobCount)
 * ```
 */
export async function generateFaasTypes(
  options: GenerateFaasTypesOptions = {},
): Promise<GenerateFaasTypesResult> {
  const logger = options.logger ?? new Logger('FaasJs:Typegen')
  const { root: projectRoot } = resolveServerConfig(options.root ?? process.cwd(), logger)
  const srcRoot = join(projectRoot, 'src')
  const output = join(srcRoot, '.faasjs', 'types.d.ts')

  if (!existsSync(srcRoot)) throw Error(`[faas types] Source directory not found: ${srcRoot}`)

  const { apiFiles, jobFiles } = await readTypegenFiles(srcRoot)
  const routeMap = new Map<string, RouteTypeItem>()
  const jobMap = new Map<string, JobTypeItem>()

  for (const file of apiFiles) {
    const { route, priority } = toRoute(srcRoot, file)
    const prev = routeMap.get(route)

    if (prev && priority <= prev.priority) continue

    routeMap.set(route, {
      route,
      importPath: toImportPath(output, file),
      priority,
    })
  }

  for (const file of jobFiles) {
    const jobPath = toJobPath(srcRoot, file)
    const previous = jobMap.get(jobPath)

    if (previous) {
      throw Error(
        `[faas types] Duplicate job path ${JSON.stringify(jobPath)} from ${previous.file} and ${file}`,
      )
    }

    jobMap.set(jobPath, {
      jobPath,
      importPath: toImportPath(output, file),
      file,
    })
  }

  const routeItems = Array.from(routeMap.values()).sort((a, b) => a.route.localeCompare(b.route))
  const jobItems = Array.from(jobMap.values()).sort((a, b) => a.jobPath.localeCompare(b.jobPath))
  const content = formatTypes(routeItems, jobItems)

  let changed = true

  try {
    if ((await readFile(output, 'utf8')) === content) changed = false
  } catch {}

  if (changed) {
    await mkdir(dirname(output), {
      recursive: true,
    })
    await writeFile(output, content)
  }

  return {
    output,
    changed,
    fileCount: apiFiles.length,
    routeCount: routeItems.length,
    jobCount: jobItems.length,
  }
}
