import { existsSync } from 'node:fs'
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join, relative } from 'node:path'

import { Logger } from '@faasjs/node-utils'

import { resolveServerConfig } from '../shared/server_config.ts'

type RouteTypeItem = {
  route: string
  importPath: string
  priority: number
}

/**
 * Options for generating `@faasjs/types` route declarations.
 */
export type GenerateFaasTypesOptions = {
  /**
   * Project root used to resolve `src/` and emit `src/.faasjs/types.d.ts`.
   *
   * @default process.cwd()
   */
  root?: string
  /**
   * Logger used to report generation progress.
   */
  logger?: Logger
}

/**
 * Summary returned by {@link generateFaasTypes}.
 */
export type GenerateFaasTypesResult = {
  /**
   * Output path of the generated declaration file.
   */
  output: string
  /**
   * Whether the generator wrote new content to disk.
   */
  changed: boolean
  /**
   * Number of `*.api.ts` files discovered under `src/`.
   */
  fileCount: number
  /**
   * Number of route entries emitted into the declaration file.
   */
  routeCount: number
}

function normalizeRoute(path: string): string {
  const normalized = path.replace(/\\/g, '/').replace(/\/+/g, '/')

  if (!normalized.length || normalized === '/') return '/'

  return normalized.endsWith('/') ? normalized.slice(0, -1) : normalized
}

function toTypegenRoute(route: string): string {
  return route === '/' ? '/' : route.replace(/^\/+/, '')
}

function toRoute(srcRoot: string, file: string): { route: string; priority: number } {
  const noTsPath = relative(srcRoot, file).replace(/\\/g, '/').replace(/\.ts$/, '')

  if (noTsPath === 'index.api') return { route: '/', priority: 2 }

  if (noTsPath === 'default.api') return { route: '/*', priority: 1 }

  if (noTsPath.endsWith('/index.api'))
    return {
      route: normalizeRoute(`/${noTsPath.slice(0, -'/index.api'.length)}`),
      priority: 2,
    }

  if (noTsPath.endsWith('/default.api'))
    return {
      route: normalizeRoute(`/${noTsPath.slice(0, -'/default.api'.length)}/*`),
      priority: 1,
    }

  if (noTsPath.endsWith('.api'))
    return {
      route: normalizeRoute(`/${noTsPath.slice(0, -'.api'.length)}`),
      priority: 3,
    }

  throw Error(`[faas types] Invalid API filename: ${file}`)
}

function toImportPath(fromFile: string, targetFile: string): string {
  const importPath = relative(dirname(fromFile), targetFile)
    .replace(/\\/g, '/')
    .replace(/\.ts$/, '')

  if (importPath.startsWith('.')) return importPath

  return `./${importPath}`
}

async function readApiFiles(dir: string): Promise<string[]> {
  const result: string[] = []
  const pendingDirs = [dir]

  while (pendingDirs.length) {
    const currentDir = pendingDirs.pop() as string
    const entries = await readdir(currentDir, {
      withFileTypes: true,
    })

    for (const entry of entries) {
      if (entry.name === '.faasjs' || entry.name === 'node_modules') continue

      const filePath = join(currentDir, entry.name)

      if (entry.isDirectory()) {
        pendingDirs.push(filePath)
        continue
      }

      if (entry.isFile() && entry.name.endsWith('.api.ts')) result.push(filePath)
    }
  }

  return result.sort((a, b) => a.localeCompare(b))
}

function formatTypes(items: RouteTypeItem[]): string {
  const actionLines = items.map((item) => {
    return `    ${JSON.stringify(toTypegenRoute(item.route))}: InferFaasAction<InferFaasApi<typeof import(${JSON.stringify(item.importPath)})>>`
  })

  return `/**
 * Generated by @faasjs/dev.
 *
 * Do not edit this file manually.
 */
import type { InferFaasAction, InferFaasApi } from '@faasjs/types'

declare module '@faasjs/types' {
  interface FaasActions {
${actionLines.length ? `${actionLines.join('\n')}\n` : ''}  }
}
`
}

/**
 * Determine whether a file change should trigger Faas type generation.
 *
 * @param {string} filePath - Absolute or relative path reported by a file watcher.
 * @returns `true` when the changed file can affect generated route declarations.
 * @example
 * ```ts
 * import { isTypegenInputFile } from '@faasjs/dev'
 *
 * isTypegenInputFile('src/orders/create.api.ts') // true
 * isTypegenInputFile('src/orders/service.ts') // false
 * ```
 */
export function isTypegenInputFile(filePath: string): boolean {
  return filePath.endsWith('.api.ts') || /(^|[\\/])faas\.ya?ml$/.test(filePath)
}

/**
 * @deprecated Use {@link isTypegenInputFile} instead.
 */
export function isTypegenSourceFile(filePath: string): boolean {
  return isTypegenInputFile(filePath)
}

/**
 * Generate `src/.faasjs/types.d.ts` for a FaasJS project.
 *
 * The generator scans the `src/` tree for `.api.ts` files, converts file
 * names into routes, and keeps the most specific file when multiple files
 * resolve to the same route.
 *
 * @param {GenerateFaasTypesOptions} [options] - Project root and logger overrides.
 * @param {string} [options.root] - Project root used to resolve `src/` and the output file.
 * @param {Logger} [options.logger] - Logger used to report generation progress.
 * @returns Summary describing the generated file and discovered routes.
 * @throws {Error} When the resolved `src/` directory does not exist.
 * @example
 * ```ts
 * import { generateFaasTypes } from '@faasjs/dev'
 *
 * const result = await generateFaasTypes({
 *   root: process.cwd(),
 * })
 *
 * console.log(result.output, result.routeCount)
 * ```
 */
export async function generateFaasTypes(
  options: GenerateFaasTypesOptions = {},
): Promise<GenerateFaasTypesResult> {
  const logger = options.logger ?? new Logger('FaasJs:Typegen')
  const { root: projectRoot } = resolveServerConfig(options.root ?? process.cwd(), logger)
  const srcRoot = join(projectRoot, 'src')
  const output = join(srcRoot, '.faasjs', 'types.d.ts')

  if (!existsSync(srcRoot)) throw Error(`[faas types] Source directory not found: ${srcRoot}`)

  const files = await readApiFiles(srcRoot)
  const routeMap = new Map<string, RouteTypeItem>()

  for (const file of files) {
    const { route, priority } = toRoute(srcRoot, file)
    const prev = routeMap.get(route)

    if (prev && priority <= prev.priority) continue

    routeMap.set(route, {
      route,
      importPath: toImportPath(output, file),
      priority,
    })
  }

  const items = Array.from(routeMap.values()).sort((a, b) => a.route.localeCompare(b.route))
  const content = formatTypes(items)

  let changed = true

  try {
    if ((await readFile(output, 'utf8')) === content) changed = false
  } catch {}

  if (changed) {
    await mkdir(dirname(output), {
      recursive: true,
    })
    await writeFile(output, content)
  }

  return {
    output,
    changed,
    fileCount: files.length,
    routeCount: items.length,
  }
}
