/**
 * Generated by @faasjs/dev.
 *
 * Do not edit this file manually.
 */
import type { InferFaasAction } from '@faasjs/types'

declare module '@faasjs/types' {
  interface FaasActions {
    "features/home/api/hello": InferFaasAction<typeof import("../features/home/api/hello.api")>
  }
}
