import { type Dispatch, type SetStateAction, useState } from 'react'

/**
 * Setter map generated by {@link useSplittingState} for each state key.
 *
 * @template T - Object shape whose keys receive generated setter functions.
 */
export type StateSetters<T> = {
  [K in keyof T as K extends string
    ? K extends `${infer First}${infer Rest}`
      ? `set${Capitalize<First>}${Rest}`
      : never
    : never]: Dispatch<SetStateAction<T[K]>>
}

/**
 * State object returned by {@link useSplittingState}, including generated setters.
 *
 * @template T - Object shape returned together with generated setter functions.
 */
export type StatesWithSetters<T> = T & StateSetters<T>

/**
 * Create local state entries and matching setters for each key in an object.
 *
 * @template T - A generic type that extends a record with string keys and any values.
 * @param {T} initialStates - Object whose keys become state values and `setXxx` setters.
 * @returns {StatesWithSetters<T>} Object containing the original keys plus generated setter functions.
 *
 * @example
 * ```tsx
 * function Counter() {
 *   const { count, setCount, name, setName } = useSplittingState({ count: 0, name: 'John' })
 *
 *   return <>{name}: {count}</>
 * }
 * ```
 */
export function useSplittingState<T extends Record<string, unknown>>(initialStates: T) {
  const states = {} as StatesWithSetters<T>

  for (const key of Object.keys(initialStates) as (keyof T)[]) {
    const state = useState(initialStates[key])

    Object.assign(states, {
      [key]: state[0],
      [`set${String(key).charAt(0).toUpperCase()}${String(key).slice(1)}`]: state[1],
    })
  }

  return states
}
