/**
 * Generated by @faasjs/dev.
 *
 * Do not edit this file manually.
 */
import type { InferFaasAction } from '@faasjs/types'

declare module '@faasjs/types' {
  interface FaasActions {
    "features/auth/api/me": InferFaasAction<typeof import("../features/auth/api/me.api")>
    "features/users/api/create": InferFaasAction<typeof import("../features/users/api/create.api")>
    "features/users/api/detail": InferFaasAction<typeof import("../features/users/api/detail.api")>
    "features/users/api/list": InferFaasAction<typeof import("../features/users/api/list.api")>
    "features/users/api/update": InferFaasAction<typeof import("../features/users/api/update.api")>
  }
}
