import { type Dispatch, type RefObject, type SetStateAction, useState } from 'react'

import { useStateRef } from '../useStateRef'

/**
 * Setter map generated by {@link useStates} for each state key.
 *
 * @template T - Object shape whose keys receive generated setter functions.
 */
export type StateSetters<T> = {
  [K in keyof T as K extends string
    ? K extends `${infer First}${infer Rest}`
      ? `set${Capitalize<First>}${Rest}`
      : never
    : never]: Dispatch<SetStateAction<T[K]>>
}

/**
 * Ref map generated by {@link useStatesRef} for each state key.
 *
 * @template T - Object shape whose keys receive generated ref objects.
 */
export type StateRefs<T> = {
  [K in keyof T as K extends string ? `${K}Ref` : never]: RefObject<T[K]>
}

/**
 * State object returned by {@link useStates}, including generated setters.
 *
 * @template T - Object shape returned together with generated setter functions.
 */
export type StatesWithSetters<T> = T & StateSetters<T>

/**
 * State object returned by {@link useStatesRef}, including generated setters and refs.
 *
 * @template T - Object shape returned together with generated setter functions and refs.
 */
export type StatesWithSettersAndRefs<T> = T & StateSetters<T> & StateRefs<T>

/**
 * Create local state entries and matching setters for each key in an object.
 *
 * @template T - A generic type that extends a record with string keys and any values.
 * @param {T} initialStates - Object whose keys become state values and `setXxx` setters.
 * @returns {StatesWithSetters<T>} Object containing the original keys plus generated setter functions.
 *
 * @example
 * ```tsx
 * function Counter() {
 *   const { count, setCount, name, setName } = useStates({ count: 0, name: 'John' })
 *
 *   return <>{name}: {count}</>
 * }
 * ```
 */
export function useStates<T extends Record<string, unknown>>(
  initialStates: T,
): StatesWithSetters<T> {
  const states = {} as StatesWithSetters<T>

  for (const key of Object.keys(initialStates) as (keyof T)[]) {
    const state = useState(initialStates[key])

    Object.assign(states, {
      [key]: state[0],
      [`set${String(key).charAt(0).toUpperCase()}${String(key).slice(1)}`]: state[1],
    })
  }

  return states
}

/**
 * Create local state entries, matching setters, and refs for each key in an object.
 *
 * @template T - A generic type that extends a record with string keys and any values.
 * @param {T} initialStates - Object whose keys become state values, `setXxx` setters, and `xxxRef` refs.
 * @returns {StatesWithSettersAndRefs<T>} Object containing the original keys plus generated setter functions and refs.
 *
 * @example
 * ```tsx
 * function Counter() {
 *   const { count, setCount, countRef } = useStatesRef({ count: 0 })
 *
 *   return <button onClick={() => setCount(countRef.current + 1)}>{count}</button>
 * }
 * ```
 */
export function useStatesRef<T extends Record<string, unknown>>(
  initialStates: T,
): StatesWithSettersAndRefs<T> {
  const states = {} as StatesWithSettersAndRefs<T>

  for (const key of Object.keys(initialStates) as (keyof T)[]) {
    const state = useStateRef(initialStates[key])

    Object.assign(states, {
      [key]: state[0],
      [`set${String(key).charAt(0).toUpperCase()}${String(key).slice(1)}`]: state[1],
      [`${String(key)}Ref`]: state[2],
    })
  }

  return states
}
