import {
  type Dispatch,
  type RefObject,
  type SetStateAction,
  useEffect,
  useRef,
  useState,
} from 'react'

/**
 * Setter map generated by {@link useStates} for each state key.
 *
 * @template T - Object shape whose keys receive generated setter functions.
 */
export type StateSetters<T> = {
  [K in keyof T as K extends string
    ? K extends `${infer First}${infer Rest}`
      ? `set${Capitalize<First>}${Rest}`
      : never
    : never]: Dispatch<SetStateAction<T[K]>>
}

/**
 * Ref map generated by {@link useStatesRef} for each state key.
 *
 * @template T - Object shape whose keys receive generated ref objects.
 */
export type StateRefs<T> = {
  [K in keyof T as K extends string ? `${K}Ref` : never]: RefObject<T[K]>
}

/**
 * State object returned by {@link useStates}, including generated setters.
 *
 * @template T - Object shape returned together with generated setter functions.
 */
export type StatesWithSetters<T> = T & StateSetters<T>

/**
 * State object returned by {@link useStatesRef}, including generated setters and refs.
 *
 * @template T - Object shape returned together with generated setter functions and refs.
 */
export type StatesWithSettersAndRefs<T> = T & StateSetters<T> & StateRefs<T>

function setterName(key: string): string {
  return `set${key.charAt(0).toUpperCase()}${key.slice(1)}`
}

function hasOwn(object: Record<string, unknown>, key: string): boolean {
  return Object.prototype.hasOwnProperty.call(object, key)
}

/**
 * Create local state entries and matching setters for each key in an object.
 *
 * @template T - A generic type that extends a record with string keys and any values.
 * @param {T} initialStates - Object whose keys become state values and `setXxx` setters.
 * @returns {StatesWithSetters<T>} Object containing the original keys plus generated setter functions.
 *
 * @example
 * ```tsx
 * function Counter() {
 *   const { count, setCount, name, setName } = useStates({ count: 0, name: 'John' })
 *
 *   return <>{name}: {count}</>
 * }
 * ```
 */
export function useStates<T extends Record<string, unknown>>(
  initialStates: T,
): StatesWithSetters<T> {
  const [values, setValues] = useState<Record<string, unknown>>(() => ({ ...initialStates }))
  const initialValues = useRef<Record<string, unknown>>({ ...initialStates })
  const setters = useRef(new Map<string, Dispatch<SetStateAction<unknown>>>())
  const states = Object.create(null) as StatesWithSetters<T>

  for (const key of Object.keys(initialStates)) {
    if (!hasOwn(initialValues.current, key)) initialValues.current[key] = initialStates[key]

    let setter = setters.current.get(key)

    if (!setter) {
      setter = (action) => {
        setValues((previousValues) => {
          const previousValue = hasOwn(previousValues, key)
            ? previousValues[key]
            : initialValues.current[key]
          const nextValue =
            typeof action === 'function'
              ? (action as (previousState: unknown) => unknown)(previousValue)
              : action

          if (hasOwn(previousValues, key) && Object.is(previousValue, nextValue))
            return previousValues

          return {
            ...previousValues,
            [key]: nextValue,
          }
        })
      }

      setters.current.set(key, setter)
    }

    Object.assign(states, {
      [key]: hasOwn(values, key) ? values[key] : initialValues.current[key],
      [setterName(key)]: setter,
    })
  }

  return states
}

/**
 * Create local state entries, matching setters, and refs for each key in an object.
 *
 * @template T - A generic type that extends a record with string keys and any values.
 * @param {T} initialStates - Object whose keys become state values, `setXxx` setters, and `xxxRef` refs.
 * @returns {StatesWithSettersAndRefs<T>} Object containing the original keys plus generated setter functions and refs.
 *
 * @example
 * ```tsx
 * function Counter() {
 *   const { count, setCount, countRef } = useStatesRef({ count: 0 })
 *
 *   return <button onClick={() => setCount(countRef.current + 1)}>{count}</button>
 * }
 * ```
 */
export function useStatesRef<T extends Record<string, unknown>>(
  initialStates: T,
): StatesWithSettersAndRefs<T> {
  const states = useStates(initialStates)
  const refs = useRef(new Map<string, RefObject<unknown>>())
  const result = { ...states } as StatesWithSettersAndRefs<T>

  for (const key of Object.keys(initialStates)) {
    let ref = refs.current.get(key)

    if (!ref) {
      ref = { current: states[key] }
      refs.current.set(key, ref)
    }

    Object.assign(result, { [`${key}Ref`]: ref })
  }

  useEffect(() => {
    for (const key of Object.keys(initialStates)) {
      const ref = refs.current.get(key)
      if (ref) ref.current = states[key]
    }
  }, [initialStates, states])

  return result
}
