import { type Dispatch, type SetStateAction, useSyncExternalStore } from 'react'

/**
 * Ref object exposed by {@link createProxyStates} for reading the latest shared state value.
 *
 * @template T - Shared state value type.
 */
export type ProxyStateRef<T> = Readonly<{
  current: T
}>

/**
 * Hook map generated by {@link createProxyStates} for each shared state key.
 *
 * @template T - Shared state object shape.
 */
export type ProxyStateHooks<T> = {
  [K in keyof T as K extends string ? `use${Capitalize<K>}` : never]: () => T[K]
}

/**
 * Setter map generated by {@link createProxyStates} for each shared state key.
 *
 * @template T - Shared state object shape.
 */
export type ProxyStateSetters<T> = {
  [K in keyof T as K extends string ? `set${Capitalize<K>}` : never]: Dispatch<SetStateAction<T[K]>>
}

/**
 * Ref map generated by {@link createProxyStates} for each shared state key.
 *
 * @template T - Shared state object shape.
 */
export type ProxyStateRefs<T> = {
  [K in keyof T as K extends string ? `${K}Ref` : never]: ProxyStateRef<T[K]>
}

/**
 * Shared state helpers returned by {@link createProxyStates}.
 *
 * @template T - Shared state object shape.
 */
export type ProxyStates<T> = ProxyStateHooks<T> & ProxyStateSetters<T> & ProxyStateRefs<T>

type ProxyStateSnapshot<T> = {
  value: T
  version: number
}

function upperFirst(value: string) {
  return `${value.charAt(0).toUpperCase()}${value.slice(1)}`
}

function createProxyState<T>(defaultValue: T) {
  const listeners = new Set<() => void>()
  let snapshot: ProxyStateSnapshot<T> = { value: defaultValue, version: 0 }
  const state = new Proxy<{ value: T }>(
    { value: defaultValue },
    {
      set(target, property, value) {
        const updated = Reflect.set(target, property, value)

        if (!updated || property !== 'value') return updated

        snapshot = {
          value: value as T,
          version: snapshot.version + 1,
        }

        for (const listener of listeners) listener()

        return true
      },
    },
  )

  const getSnapshot = () => snapshot

  const subscribe = (onStoreChange: () => void) => {
    listeners.add(onStoreChange)

    return () => {
      listeners.delete(onStoreChange)
    }
  }

  const use = () => useSyncExternalStore(subscribe, getSnapshot, getSnapshot).value

  const set: Dispatch<SetStateAction<T>> = (value) => {
    const previousValue = Reflect.get(state, 'value') as T
    const nextValue =
      typeof value === 'function' ? (value as (previousValue: T) => T)(previousValue) : value

    Reflect.set(state, 'value', nextValue)
  }

  const ref: ProxyStateRef<T> = {
    get current() {
      return Reflect.get(state, 'value') as T
    },
  }

  return {
    ref,
    set,
    use,
  }
}

/**
 * Create Proxy-backed shared states with generated hooks, setters, and latest-value refs.
 *
 * Each key receives an independent external store. Components using a generated hook re-render
 * when the matching setter runs, and code outside React can read the latest value from the
 * generated ref.
 *
 * @template T - Shared state object shape.
 * @param {T} defaultStates - Initial values used to create shared state entries.
 * @returns {ProxyStates<T>} Generated `useXxx`, `setXxx`, and `xxxRef` helpers for each key.
 *
 * @example
 * ```tsx
 * import { createProxyStates } from '@faasjs/react'
 *
 * export const { useText, setText, textRef } = createProxyStates({
 *   text: '',
 * })
 *
 * function Preview() {
 *   const text = useText()
 *
 *   return <span>{text}</span>
 * }
 *
 * setText('updated')
 * console.log(textRef.current)
 * ```
 */
export function createProxyStates<T extends Record<string, unknown>>(
  defaultStates: T,
): ProxyStates<T> {
  const states = {} as ProxyStates<T>

  for (const key of Object.keys(defaultStates) as (keyof T & string)[]) {
    const state = createProxyState(defaultStates[key])
    const name = upperFirst(key)

    Object.assign(states, {
      [`${key}Ref`]: state.ref,
      [`set${name}`]: state.set,
      [`use${name}`]: state.use,
    })
  }

  return states
}
