name: Build nginx image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - main
    paths:
      - 'images/nginx/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: faasjs/nginx:${{ github.sha }},faasjs/nginx:alpine,faasjs/nginx:latest
          platforms: linux/x86_64,linux/amd64,linux/arm64
          context: ./images/nginx
          cache-from: type=gha
          cache-to: type=gha,mode=max
