name: Testing

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - packages/**
      - .github/workflows/unit.yml
      - .mise.toml
      - package-lock.json
      - package.json
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: 24
      - run: |
          npm install
          npm run pack
          npm run lint
          npm run ci
      - uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
