name: Vitest

on:
  workflow_dispatch:
  push:
    branches:
      - vitest
    paths:
      - packages/**
      - .github/workflows/unit.yml
      - package-lock.json
      - package.json
      - vitest.workspace.ts
  pull_request:
    paths:
      - .github/workflows/unit.yml
      - packages/**
      - package-lock.json
      - package.json

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
      mysql:
        image: mysql
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
        ports:
          - 3306:3306
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 22
      - name: Install
        run: npm install
      - name: Run Tests
        run: node --run vitest
